# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\wildbits\main.ui',
# licensing of '.\wildbits\main.ui' applies.
#
# Created: Wed Jun 12 06:38:00 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_sarc = QtWidgets.QWidget()
        self.tab_sarc.setObjectName("tab_sarc")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_sarc)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab_sarc)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.treeSarc = QtWidgets.QTreeWidget(self.groupBox)
        self.treeSarc.setObjectName("treeSarc")
        self.treeSarc.header().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.treeSarc)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnNewSarc = QtWidgets.QPushButton(self.groupBox)
        self.btnNewSarc.setStyleSheet("padding: 4 8 ")
        self.btnNewSarc.setObjectName("btnNewSarc")
        self.horizontalLayout.addWidget(self.btnNewSarc)
        self.btnOpenSarc = QtWidgets.QPushButton(self.groupBox)
        self.btnOpenSarc.setStyleSheet("padding: 4 8 ")
        self.btnOpenSarc.setObjectName("btnOpenSarc")
        self.horizontalLayout.addWidget(self.btnOpenSarc)
        self.btnAddSarc = QtWidgets.QPushButton(self.groupBox)
        self.btnAddSarc.setEnabled(False)
        self.btnAddSarc.setStyleSheet("padding: 4 8 ")
        self.btnAddSarc.setObjectName("btnAddSarc")
        self.horizontalLayout.addWidget(self.btnAddSarc)
        self.btnUpdateSarc = QtWidgets.QPushButton(self.groupBox)
        self.btnUpdateSarc.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUpdateSarc.sizePolicy().hasHeightForWidth())
        self.btnUpdateSarc.setSizePolicy(sizePolicy)
        self.btnUpdateSarc.setStyleSheet("padding: 4 8 ")
        self.btnUpdateSarc.setObjectName("btnUpdateSarc")
        self.horizontalLayout.addWidget(self.btnUpdateSarc)
        self.btnDeleteSarc = QtWidgets.QPushButton(self.groupBox)
        self.btnDeleteSarc.setEnabled(False)
        self.btnDeleteSarc.setStyleSheet("padding: 4 8 ")
        self.btnDeleteSarc.setObjectName("btnDeleteSarc")
        self.horizontalLayout.addWidget(self.btnDeleteSarc)
        self.btnExtSarc = QtWidgets.QPushButton(self.groupBox)
        self.btnExtSarc.setEnabled(False)
        self.btnExtSarc.setStyleSheet("padding: 4 8 ")
        self.btnExtSarc.setObjectName("btnExtSarc")
        self.horizontalLayout.addWidget(self.btnExtSarc)
        self.btnSaveSarc = QtWidgets.QPushButton(self.groupBox)
        self.btnSaveSarc.setEnabled(False)
        self.btnSaveSarc.setStyleSheet("padding: 4 8 ")
        self.btnSaveSarc.setObjectName("btnSaveSarc")
        self.horizontalLayout.addWidget(self.btnSaveSarc)
        self.btnSaveAsSarc = QtWidgets.QPushButton(self.groupBox)
        self.btnSaveAsSarc.setEnabled(False)
        self.btnSaveAsSarc.setStyleSheet("padding: 4 8 ")
        self.btnSaveAsSarc.setObjectName("btnSaveAsSarc")
        self.horizontalLayout.addWidget(self.btnSaveAsSarc)
        self.chkBeSarc = QtWidgets.QCheckBox(self.groupBox)
        self.chkBeSarc.setEnabled(True)
        self.chkBeSarc.setChecked(True)
        self.chkBeSarc.setObjectName("chkBeSarc")
        self.horizontalLayout.addWidget(self.chkBeSarc)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_sarc)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnExtractSarc = QtWidgets.QPushButton(self.groupBox_2)
        self.btnExtractSarc.setStyleSheet("padding: 4 8;")
        self.btnExtractSarc.setObjectName("btnExtractSarc")
        self.horizontalLayout_2.addWidget(self.btnExtractSarc)
        self.btnCreateSarc = QtWidgets.QPushButton(self.groupBox_2)
        self.btnCreateSarc.setStyleSheet("padding: 4 8")
        self.btnCreateSarc.setObjectName("btnCreateSarc")
        self.horizontalLayout_2.addWidget(self.btnCreateSarc)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_sarc, "")
        self.tab_rstb = QtWidgets.QWidget()
        self.tab_rstb.setObjectName("tab_rstb")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_rstb)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.tab_rstb)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.tblRstb = QtWidgets.QTableWidget(self.tab_rstb)
        self.tblRstb.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tblRstb.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblRstb.setShowGrid(False)
        self.tblRstb.setObjectName("tblRstb")
        self.tblRstb.setColumnCount(3)
        self.tblRstb.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblRstb.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblRstb.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblRstb.setHorizontalHeaderItem(2, item)
        self.tblRstb.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tblRstb)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnOpenRstb = QtWidgets.QPushButton(self.tab_rstb)
        self.btnOpenRstb.setStyleSheet("padding: 4 8;")
        self.btnOpenRstb.setObjectName("btnOpenRstb")
        self.horizontalLayout_3.addWidget(self.btnOpenRstb)
        self.btnAddRstb = QtWidgets.QPushButton(self.tab_rstb)
        self.btnAddRstb.setEnabled(False)
        self.btnAddRstb.setStyleSheet("padding: 4 8;")
        self.btnAddRstb.setObjectName("btnAddRstb")
        self.horizontalLayout_3.addWidget(self.btnAddRstb)
        self.btnUpdateRstb = QtWidgets.QPushButton(self.tab_rstb)
        self.btnUpdateRstb.setEnabled(False)
        self.btnUpdateRstb.setStyleSheet("padding: 4 8;")
        self.btnUpdateRstb.setObjectName("btnUpdateRstb")
        self.horizontalLayout_3.addWidget(self.btnUpdateRstb)
        self.btnDeleteRstb = QtWidgets.QPushButton(self.tab_rstb)
        self.btnDeleteRstb.setEnabled(False)
        self.btnDeleteRstb.setStyleSheet("padding: 4 8;")
        self.btnDeleteRstb.setObjectName("btnDeleteRstb")
        self.horizontalLayout_3.addWidget(self.btnDeleteRstb)
        self.btnSaveRstb = QtWidgets.QPushButton(self.tab_rstb)
        self.btnSaveRstb.setEnabled(False)
        self.btnSaveRstb.setStyleSheet("padding: 4 8;")
        self.btnSaveRstb.setObjectName("btnSaveRstb")
        self.horizontalLayout_3.addWidget(self.btnSaveRstb)
        self.btnSaveAsRstb = QtWidgets.QPushButton(self.tab_rstb)
        self.btnSaveAsRstb.setEnabled(False)
        self.btnSaveAsRstb.setStyleSheet("padding: 4 8;")
        self.btnSaveAsRstb.setObjectName("btnSaveAsRstb")
        self.horizontalLayout_3.addWidget(self.btnSaveAsRstb)
        self.chkBeRstb = QtWidgets.QCheckBox(self.tab_rstb)
        self.chkBeRstb.setEnabled(False)
        self.chkBeRstb.setObjectName("chkBeRstb")
        self.horizontalLayout_3.addWidget(self.chkBeRstb)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.tab_rstb)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.txtFilterRstb = QtWidgets.QLineEdit(self.tab_rstb)
        self.txtFilterRstb.setObjectName("txtFilterRstb")
        self.horizontalLayout_3.addWidget(self.txtFilterRstb)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_rstb, "")
        self.tab_files = QtWidgets.QWidget()
        self.tab_files.setObjectName("tab_files")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_files)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btnNewYaml = QtWidgets.QPushButton(self.tab_files)
        self.btnNewYaml.setObjectName("btnNewYaml")
        self.verticalLayout_4.addWidget(self.btnNewYaml)
        self.btnOpenYaml = QtWidgets.QPushButton(self.tab_files)
        self.btnOpenYaml.setObjectName("btnOpenYaml")
        self.verticalLayout_4.addWidget(self.btnOpenYaml)
        self.btnYamlEditor = QtWidgets.QPushButton(self.tab_files)
        self.btnYamlEditor.setEnabled(False)
        self.btnYamlEditor.setObjectName("btnYamlEditor")
        self.verticalLayout_4.addWidget(self.btnYamlEditor)
        self.btnExportYaml = QtWidgets.QPushButton(self.tab_files)
        self.btnExportYaml.setEnabled(False)
        self.btnExportYaml.setObjectName("btnExportYaml")
        self.verticalLayout_4.addWidget(self.btnExportYaml)
        self.btnSaveYaml = QtWidgets.QPushButton(self.tab_files)
        self.btnSaveYaml.setEnabled(False)
        self.btnSaveYaml.setObjectName("btnSaveYaml")
        self.verticalLayout_4.addWidget(self.btnSaveYaml)
        self.btnSaveAsYaml = QtWidgets.QPushButton(self.tab_files)
        self.btnSaveAsYaml.setEnabled(False)
        self.btnSaveAsYaml.setObjectName("btnSaveAsYaml")
        self.verticalLayout_4.addWidget(self.btnSaveAsYaml)
        self.chkBeYaml = QtWidgets.QCheckBox(self.tab_files)
        self.chkBeYaml.setObjectName("chkBeYaml")
        self.verticalLayout_4.addWidget(self.chkBeYaml)
        self.label_4 = QtWidgets.QLabel(self.tab_files)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.txtRstbYaml = QtWidgets.QLineEdit(self.tab_files)
        self.txtRstbYaml.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtRstbYaml.sizePolicy().hasHeightForWidth())
        self.txtRstbYaml.setSizePolicy(sizePolicy)
        self.txtRstbYaml.setReadOnly(True)
        self.txtRstbYaml.setObjectName("txtRstbYaml")
        self.verticalLayout_4.addWidget(self.txtRstbYaml)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.tab_files)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_5.addWidget(self.label_5)
        self.txtYaml = QtWidgets.QTextEdit(self.tab_files)
        self.txtYaml.setEnabled(False)
        self.txtYaml.setReadOnly(True)
        self.txtYaml.setObjectName("txtYaml")
        self.verticalLayout_5.addWidget(self.txtYaml)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_files, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Wild Bits - BotW Python Tools", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "SARC Editor", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "SARC Contents:", None, -1))
        self.treeSarc.headerItem().setText(0, QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.treeSarc.headerItem().setText(1, QtWidgets.QApplication.translate("MainWindow", "Size", None, -1))
        self.btnNewSarc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Creates an empty SARC archive", None, -1))
        self.btnNewSarc.setText(QtWidgets.QApplication.translate("MainWindow", "New SARC", None, -1))
        self.btnOpenSarc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Opens a SARC", None, -1))
        self.btnOpenSarc.setText(QtWidgets.QApplication.translate("MainWindow", "Open...", None, -1))
        self.btnAddSarc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Adds a single file to the open SARC", None, -1))
        self.btnAddSarc.setText(QtWidgets.QApplication.translate("MainWindow", "Add File...", None, -1))
        self.btnUpdateSarc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Adds all of the files in a selected folder to the SARC, replacing existing files", None, -1))
        self.btnUpdateSarc.setText(QtWidgets.QApplication.translate("MainWindow", "Update from Folder...", None, -1))
        self.btnDeleteSarc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Deletes the selected file or directory from the open SARC", None, -1))
        self.btnDeleteSarc.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.btnExtSarc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Extracts the selected file or directory from the open SARC", None, -1))
        self.btnExtSarc.setText(QtWidgets.QApplication.translate("MainWindow", "Extract...", None, -1))
        self.btnSaveSarc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Saves changes to the open SARC", None, -1))
        self.btnSaveSarc.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.btnSaveAsSarc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Saves the open SARC as a new file", None, -1))
        self.btnSaveAsSarc.setText(QtWidgets.QApplication.translate("MainWindow", "Save As...", None, -1))
        self.chkBeSarc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Specifies whether the current SARC archive is in big endian format (for Wii U) or not (for Switch)", None, -1))
        self.chkBeSarc.setText(QtWidgets.QApplication.translate("MainWindow", "Big Endian (Wii U)", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("MainWindow", "Other Tools", None, -1))
        self.btnExtractSarc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Extracts all the contents of a SARC to a specified folder", None, -1))
        self.btnExtractSarc.setText(QtWidgets.QApplication.translate("MainWindow", "Extract SARC...", None, -1))
        self.btnCreateSarc.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Creates a new SARC from the contents of a specified folder", None, -1))
        self.btnCreateSarc.setText(QtWidgets.QApplication.translate("MainWindow", "Create from Folder...", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_sarc), QtWidgets.QApplication.translate("MainWindow", "SARC Tools", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("MainWindow", "RSTB Contents:", None, -1))
        self.tblRstb.horizontalHeaderItem(0).setText(QtWidgets.QApplication.translate("MainWindow", "File Name", None, -1))
        self.tblRstb.horizontalHeaderItem(1).setText(QtWidgets.QApplication.translate("MainWindow", "Hash", None, -1))
        self.tblRstb.horizontalHeaderItem(2).setText(QtWidgets.QApplication.translate("MainWindow", "Resource Size", None, -1))
        self.btnOpenRstb.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Opens an RSTB file", None, -1))
        self.btnOpenRstb.setText(QtWidgets.QApplication.translate("MainWindow", "Open...", None, -1))
        self.btnAddRstb.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Adds an entry to the current RSTB file", None, -1))
        self.btnAddRstb.setText(QtWidgets.QApplication.translate("MainWindow", "Add Entry...", None, -1))
        self.btnUpdateRstb.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Updates the size of the selected entry in the RSTB", None, -1))
        self.btnUpdateRstb.setText(QtWidgets.QApplication.translate("MainWindow", "Update...", None, -1))
        self.btnDeleteRstb.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Deletes the selected entry from the RSTB", None, -1))
        self.btnDeleteRstb.setText(QtWidgets.QApplication.translate("MainWindow", "Delete", None, -1))
        self.btnSaveRstb.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Saves changes to the current RSTB", None, -1))
        self.btnSaveRstb.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.btnSaveAsRstb.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Saves a new RSTB file", None, -1))
        self.btnSaveAsRstb.setText(QtWidgets.QApplication.translate("MainWindow", "Save As...", None, -1))
        self.chkBeRstb.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Specifies whether the current RSTB file is in big endian format (for Wii U) or not (for Switch)", None, -1))
        self.chkBeRstb.setText(QtWidgets.QApplication.translate("MainWindow", "Big Endian (Wii U)", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("MainWindow", "Search:", None, -1))
        self.txtFilterRstb.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Searches through the RSTB entries, press Enter to submit", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_rstb), QtWidgets.QApplication.translate("MainWindow", "RSTB Editor", None, -1))
        self.btnNewYaml.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Creates a new YAML document to be converted to BYAML or AAMP", None, -1))
        self.btnNewYaml.setText(QtWidgets.QApplication.translate("MainWindow", "New", None, -1))
        self.btnOpenYaml.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Opens a BYAML or AAMP file for as a YAML document", None, -1))
        self.btnOpenYaml.setText(QtWidgets.QApplication.translate("MainWindow", "Open...", None, -1))
        self.btnYamlEditor.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Opens the current YAML file in your default code editor", None, -1))
        self.btnYamlEditor.setText(QtWidgets.QApplication.translate("MainWindow", "Open in Editor", None, -1))
        self.btnExportYaml.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Exports the current YAML document", None, -1))
        self.btnExportYaml.setText(QtWidgets.QApplication.translate("MainWindow", "Export YAML...", None, -1))
        self.btnSaveYaml.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Saves the current YAML contents to the open BYAML or AAMP file", None, -1))
        self.btnSaveYaml.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.btnSaveAsYaml.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Saves the current YAML contents to a new BYAML or AAMP file", None, -1))
        self.btnSaveAsYaml.setText(QtWidgets.QApplication.translate("MainWindow", "Save As...", None, -1))
        self.chkBeYaml.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Specifies whether the current BYAML or AAMP file is in big endian format (for Wii U) or not (for Switch)", None, -1))
        self.chkBeYaml.setText(QtWidgets.QApplication.translate("MainWindow", "Big Endian\n"
"(Wii U)", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("MainWindow", "Size for RSTB:", None, -1))
        self.txtRstbYaml.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Shows the calculated size for the current file for the RSTB (BYAML only)", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("MainWindow", "Readonly Preview:", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_files), QtWidgets.QApplication.translate("MainWindow", "YAML Tools", None, -1))

